version: '3'
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: pubkeyapp
      POSTGRES_USER: pubkeyapp
      POSTGRES_PASSWORD: pubkeyapp
    volumes:
      - ./tmp/postgres:/var/lib/postgresql/data
